export const IMAGES = {
  notification: require("../assets/images/iconoir_bell-notification.svg"),
  bookmark: require("../assets/images/bookmark.svg"),
  profilePNG: require("../assets/images/profile.png"),
  wavePNG: require("../assets/images/wave.png"),
  search: require("../assets/images/search.svg"),
  filter: require("../assets/images/filter.svg"),
  location: require("../assets/images/location.svg"),
  landmark: require("../assets/images/landmark.svg"),
  man: require("../assets/images/man.png"),
  vectorBackground: require("../assets/images/vector-background.png"),
  broom: require("../assets/images/broom.svg"),
  wrench: require("../assets/images/wrench.svg"),
  brush: require("../assets/images/brush.svg"),
  washingMachine: require("../assets/images/laundry.svg"),
  plumber: require("../assets/images/plumber.svg"),
  mover: require("../assets/images/bus.svg"),
  manSalon: require("../assets/images/man-salon.svg"),
  kylee: require("../assets/images/kylee.png"),
  starBroken: require("../assets/images/star-broken.svg"),
  bookmarkBroken: require("../assets/images/bookmark-broken.svg"),
  more: require("../assets/images/more-horizontal.svg"),
  arrowBack: require("../assets/images/arrow-up-broken.svg"),
  home: require("../assets/images/home.svg"),
  bookings: require("../assets/images/bookings.svg"),
  messages: require("../assets/images/messages.svg"),
  profile: require("../assets/images/profile.svg"),
};
